monolog:
    channels: ["mandrill","oodrive","app"]
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.session_request
            max_files: 7
            channels: ["!php","!doctrine","!event","!cache","!mandrill","!oodrive","!security"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        oodrive:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.oodrive.log"
            max_files: 7
            channels: ["oodrive"]
        mandrill:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.mandrill.log"
            max_files: 7
            channels: ["mandrill"]
