# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:

    default_filter_set_settings:
        format: webp
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    webp:
        generate: true
    filter_sets:
        thumb:
            quality: 75
            format: webp
            filters:
                thumbnail:
                    size: [300, 343]
                    mode: auto
        medium:
            quality: 75
            format: webp
            filters:
                thumbnail:
                    size: [300, 400]
                    mode: auto

        detail:
            quality: 85
            format: webp
            filters:
                thumbnail:
                    size: [ 458 , 617 ]
                    mode: auto