fos_user:
    service:
        mailer: fos_user.mailer.twig_swift
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'helmi.bejaoui@esprit.tn'
        sender_name: 'helmi.bejaoui@esprit.tn'
    resetting:
        token_ttl: 86400
        email:
            from_email:
                address: 'helmi.bejaoui@esprit.tn'
                sender_name: 'helmi.bejaoui@esprit.tn'
            template: '%env(resolve:TEMPLATE)%'